language: objective-c
osx_image: xcode7.3
env:
  - DESTINATION="OS=9.3,name=iPhone 6s" SCHEME="JTAppleCalendar-Example" SDK=iphonesimulator9.3
before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
  - cd Example
  - pod install
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -workspace Example/JTAppleCalendar.xcworkspace -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION"
    -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c
notifications:
  email: false
